---
- name: Intilizing Kubernetes Cluster
  command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ k8s_master_ip }}"
  run_once: true
  delegate_to: "{{ k8s_master_ip }}"
