---
# tasks file for docker_kubernetes
- include: swap_inactive.yml
- include: remove_swap_entry.yml
- include: install_prerequiste_kubernetes.yml
- include: docker_gpg_key.yml
- include: docker_repository.yml
- include: docker_install.yml
- include: service_docker.yml
- include: add_google_gpg_key.yml
- include: add_kubernetes_repo.yml
- include: install_kubernetes_package.yml
- include: service_kubelet_persistent.yml
- include: reboot_all.yml

