---
- name: "Setting up Sudo without Password for user {{ new_user }}."
  lineinfile:
    dest: "/etc/sudoers.d/{{ new_user }}"
    line: '{{ new_user }}  ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
